export const browserCoreExamples = [
  "openwolf browser status",
  "openwolf browser start",
  "openwolf browser stop",
  "openwolf browser tabs",
  "openwolf browser open https://example.com",
  "openwolf browser focus abcd1234",
  "openwolf browser close abcd1234",
  "openwolf browser screenshot",
  "openwolf browser screenshot --full-page",
  "openwolf browser screenshot --ref 12",
  "openwolf browser snapshot",
  "openwolf browser snapshot --format aria --limit 200",
  "openwolf browser snapshot --efficient",
  "openwolf browser snapshot --labels",
];

export const browserActionExamples = [
  "openwolf browser navigate https://example.com",
  "openwolf browser resize 1280 720",
  "openwolf browser click 12 --double",
  'openwolf browser type 23 "hello" --submit',
  "openwolf browser press Enter",
  "openwolf browser hover 44",
  "openwolf browser drag 10 11",
  "openwolf browser select 9 OptionA OptionB",
  "openwolf browser upload /tmp/openwolf/uploads/file.pdf",
  'openwolf browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openwolf browser dialog --accept",
  'openwolf browser wait --text "Done"',
  "openwolf browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openwolf browser console --level error",
  "openwolf browser pdf",
];
