#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${OPENWOLF_INSTALL_E2E_IMAGE:-${WOLFBOT_INSTALL_E2E_IMAGE:-openwolf-install-e2e:local}}"
INSTALL_URL="${OPENWOLF_INSTALL_URL:-${WOLFBOT_INSTALL_URL:-https://openwolf.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
OPENWOLF_E2E_MODELS="${OPENWOLF_E2E_MODELS:-${WOLFBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e OPENWOLF_INSTALL_URL="$INSTALL_URL" \
  -e OPENWOLF_INSTALL_TAG="${OPENWOLF_INSTALL_TAG:-${WOLFBOT_INSTALL_TAG:-latest}}" \
  -e OPENWOLF_E2E_MODELS="$OPENWOLF_E2E_MODELS" \
  -e OPENWOLF_INSTALL_E2E_PREVIOUS="${OPENWOLF_INSTALL_E2E_PREVIOUS:-${WOLFBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e OPENWOLF_INSTALL_E2E_SKIP_PREVIOUS="${OPENWOLF_INSTALL_E2E_SKIP_PREVIOUS:-${WOLFBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
